spring:
  application:
    name: "liquidation-engine"

  datasource:
    url: "jdbc:mysql://localhost:3306/liquidation_engine"
    username: root
    password: NewPassword123!

    data:
      mongodb:
        uri: mongodb://localhost:27017/liquidationdb


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true