server:
  port: 8081

spring:
  application:
    name: "liquidation-engine"

  datasource:
    url: "jdbc:mysql://localhost:3306/liquidation_engine"
    username: root
    password: root

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/liquidationdb

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: liquidation-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true